/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    competitionTypes: CompetitionType;
    competitions: Competition;
    teams: Team;
    fixtures: Fixture;
    standings: Standing;
    players: Player;
    news: News;
    'news-categories': NewsCategory;
    galleries: Gallery;
    'gallery-categories': GalleryCategory;
    products: Product;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    competitionTypes: CompetitionTypesSelect<false> | CompetitionTypesSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    fixtures: FixturesSelect<false> | FixturesSelect<true>;
    standings: StandingsSelect<false> | StandingsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    general: General;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    general: GeneralSelect<false> | GeneralSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  layout?:
    | (
        | HeroBlock
        | PageHeaderBlock
        | RichTextBlock
        | NewsSectionBlock
        | FixtureListBlock
        | StandingsBlock
        | PlayerGridBlock
        | CarouselBlock
        | SponsorGridBlock
        | PartnersBlock
        | JoinUsBlock
        | CountdownBlock
        | TabBlock
        | AdSlotBlock
      )[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (string | null) | Media;
  noIndex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Hero title. Leave empty to fall back to the default title.
   */
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty to fall back to component defaults.
   */
  slides?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  variant: 'inner' | 'landing';
  pageName?: string | null;
  title?: string | null;
  subtitle?: string | null;
  /**
   * Leave empty to use component defaults.
   */
  slides?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('prose' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsSectionBlock".
 */
export interface NewsSectionBlock {
  heading?: string | null;
  layout?: ('grid' | 'list' | 'featured') | null;
  limit?: number | null;
  /**
   * Only show posts matching any of these tags. Leave empty for all.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show a "View all news" link.
   */
  showViewAll?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FixtureListBlock".
 */
export interface FixtureListBlock {
  showTitle?: boolean | null;
  title?: string | null;
  /**
   * Leave blank for all competitions.
   */
  competition?: (string | null) | Competition;
  /**
   * Leave blank for all teams.
   */
  team?: (string | null) | Team;
  /**
   * Leave empty to include all statuses.
   */
  statuses?: ('Scheduled' | 'Finished' | 'Cancelled' | 'Postponed')[] | null;
  limit?: number | null;
  sortOrder?: ('asc' | 'desc') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fixtureList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: string;
  competitionName: string;
  /**
   * e.g. "2025/2026"
   */
  season: string;
  competitionType: string | CompetitionType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitionTypes".
 */
export interface CompetitionType {
  id: string;
  competitionTypeName: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  teamName: string;
  /**
   * Abbreviation shown on compact fixture cards, e.g. "LSH".
   */
  shortName?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  teamLogo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StandingsBlock".
 */
export interface StandingsBlock {
  showTitle?: boolean | null;
  title?: string | null;
  competition: string | Competition;
  id?: string | null;
  blockName?: string | null;
  blockType: 'standings';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlayerGridBlock".
 */
export interface PlayerGridBlock {
  heading?: string | null;
  team: string | Team;
  position?: ('all' | 'Goalkeeper' | 'LinePlayer' | 'Winger' | 'PlayMaker' | 'Lateral' | 'Coach') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'playerGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  items?:
    | {
        image: string | Media;
        title: string;
        description?: string | null;
        ctaLabel?: string | null;
        ctaLink: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorGridBlock".
 */
export interface SponsorGridBlock {
  heading?: string | null;
  sponsors?:
    | {
        name: string;
        image: string | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sponsorGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  heading?: string | null;
  partners?:
    | {
        name: string;
        image: string | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JoinUsBlock".
 */
export interface JoinUsBlock {
  heading: string;
  body?: string | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  backgroundImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'joinUs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountdownBlock".
 */
export interface CountdownBlock {
  heading?: string | null;
  targetDate: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'countdown';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabBlock".
 */
export interface TabBlock {
  tabs?:
    | {
        label: string;
        content?:
          (RichTextBlock | AdSlotBlock | CarouselBlock | FixtureListBlock | StandingsBlock | PlayerGridBlock)[] | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tab';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdSlotBlock".
 */
export interface AdSlotBlock {
  /**
   * Google AdSense slot ID.
   */
  adSlot: string;
  format?: ('auto' | 'horizontal' | 'vertical' | 'rectangle') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'adSlot';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures".
 */
export interface Fixture {
  id: string;
  fixtureCode: string;
  homeTeam: string | Team;
  awayTeam: string | Team;
  homeScore?: number | null;
  awayScore?: number | null;
  startDate: string;
  venue: 'USH' | 'SHPH';
  status: 'Scheduled' | 'Finished' | 'Cancelled' | 'Postponed';
  competition: string | Competition;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings".
 */
export interface Standing {
  id: string;
  standingName: string;
  competition: string | Competition;
  competitionType?: (string | null) | CompetitionType;
  teams?:
    | {
        position: number;
        team: string | Team;
        matchesPlayed: number;
        wins: number;
        draws: number;
        losses: number;
        goalDifference: number;
        points: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: string;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  number?: number | null;
  position: 'Goalkeeper' | 'LinePlayer' | 'Winger' | 'PlayMaker' | 'Lateral' | 'Coach';
  team: string | Team;
  profilePicture?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Used in the URL: /news/<category>/<slug>
   */
  category: string | NewsCategory;
  publishedAt: string;
  /**
   * Short excerpt shown on cards and in search results.
   */
  description: string;
  featuredImage: string | Media;
  tags?: string[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Used in the URL: /news/gallery/<tag>/<slug>
   */
  tag: string | GalleryCategory;
  publishedAt: string;
  /**
   * Optional short blurb shown above the gallery.
   */
  description?: string | null;
  /**
   * Pick the Media folder that contains this gallery's images. Manage folders from the Media collection.
   */
  folder: string | FolderInterface;
  /**
   * Optional. Used as the gallery hero and on cards. Falls back to the first image in the selected folder.
   */
  coverImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  type: 'single' | 'bundle';
  active?: boolean | null;
  /**
   * Price in cents (e.g. 2500 = €25.00). For bundles this is the bundle price the customer pays.
   */
  price: number;
  image?: (string | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Information the customer must fill in per unit. On single products, one set per product unit. On bundles, one set per bundle unit (asked in addition to each child product's own fields).
   */
  customFields?:
    | {
        /**
         * Machine key, e.g. firstName
         */
        name: string;
        label: string;
        kind: 'text' | 'email' | 'phone' | 'select';
        required?: boolean | null;
        options?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Products that make up this bundle.
   */
  bundleItems?:
    | {
        product: string | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber?: string | null;
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded';
  user?: (string | null) | User;
  customerEmail: string;
  customerName?: string | null;
  customerPhone?: string | null;
  items: {
    productTitle: string;
    product?: (string | null) | Product;
    /**
     * Set when this line was expanded from a bundle cart line.
     */
    bundleParentLineId?: string | null;
    quantity: number;
    /**
     * Cents
     */
    unitPrice: number;
    /**
     * Snapshot of per-unit custom fields { firstName, size, ... }
     */
    customFieldValues?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  subtotal: number;
  total: number;
  currency: string;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'competitionTypes';
        value: string | CompetitionType;
      } | null)
    | ({
        relationTo: 'competitions';
        value: string | Competition;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'fixtures';
        value: string | Fixture;
      } | null)
    | ({
        relationTo: 'standings';
        value: string | Standing;
      } | null)
    | ({
        relationTo: 'players';
        value: string | Player;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: string | NewsCategory;
      } | null)
    | ({
        relationTo: 'galleries';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: string | GalleryCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        pageHeader?: T | PageHeaderBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        newsSection?: T | NewsSectionBlockSelect<T>;
        fixtureList?: T | FixtureListBlockSelect<T>;
        standings?: T | StandingsBlockSelect<T>;
        playerGrid?: T | PlayerGridBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        sponsorGrid?: T | SponsorGridBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        joinUs?: T | JoinUsBlockSelect<T>;
        countdown?: T | CountdownBlockSelect<T>;
        tab?: T | TabBlockSelect<T>;
        adSlot?: T | AdSlotBlockSelect<T>;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  slides?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  variant?: T;
  pageName?: T;
  title?: T;
  subtitle?: T;
  slides?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsSectionBlock_select".
 */
export interface NewsSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  layout?: T;
  limit?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  showViewAll?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FixtureListBlock_select".
 */
export interface FixtureListBlockSelect<T extends boolean = true> {
  showTitle?: T;
  title?: T;
  competition?: T;
  team?: T;
  statuses?: T;
  limit?: T;
  sortOrder?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StandingsBlock_select".
 */
export interface StandingsBlockSelect<T extends boolean = true> {
  showTitle?: T;
  title?: T;
  competition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlayerGridBlock_select".
 */
export interface PlayerGridBlockSelect<T extends boolean = true> {
  heading?: T;
  team?: T;
  position?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorGridBlock_select".
 */
export interface SponsorGridBlockSelect<T extends boolean = true> {
  heading?: T;
  sponsors?:
    | T
    | {
        name?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  heading?: T;
  partners?:
    | T
    | {
        name?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JoinUsBlock_select".
 */
export interface JoinUsBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  ctaLabel?: T;
  ctaLink?: T;
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountdownBlock_select".
 */
export interface CountdownBlockSelect<T extends boolean = true> {
  heading?: T;
  targetDate?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabBlock_select".
 */
export interface TabBlockSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        label?: T;
        content?:
          | T
          | {
              richText?: T | RichTextBlockSelect<T>;
              adSlot?: T | AdSlotBlockSelect<T>;
              carousel?: T | CarouselBlockSelect<T>;
              fixtureList?: T | FixtureListBlockSelect<T>;
              standings?: T | StandingsBlockSelect<T>;
              playerGrid?: T | PlayerGridBlockSelect<T>;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdSlotBlock_select".
 */
export interface AdSlotBlockSelect<T extends boolean = true> {
  adSlot?: T;
  format?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitionTypes_select".
 */
export interface CompetitionTypesSelect<T extends boolean = true> {
  competitionTypeName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  competitionName?: T;
  season?: T;
  competitionType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  teamName?: T;
  shortName?: T;
  generateSlug?: T;
  slug?: T;
  teamLogo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixtures_select".
 */
export interface FixturesSelect<T extends boolean = true> {
  fixtureCode?: T;
  homeTeam?: T;
  awayTeam?: T;
  homeScore?: T;
  awayScore?: T;
  startDate?: T;
  venue?: T;
  status?: T;
  competition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standings_select".
 */
export interface StandingsSelect<T extends boolean = true> {
  standingName?: T;
  competition?: T;
  competitionType?: T;
  teams?:
    | T
    | {
        position?: T;
        team?: T;
        matchesPlayed?: T;
        wins?: T;
        draws?: T;
        losses?: T;
        goalDifference?: T;
        points?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  number?: T;
  position?: T;
  team?: T;
  profilePicture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  description?: T;
  featuredImage?: T;
  tags?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  tag?: T;
  publishedAt?: T;
  description?: T;
  folder?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  type?: T;
  active?: T;
  price?: T;
  image?: T;
  description?: T;
  customFields?:
    | T
    | {
        name?: T;
        label?: T;
        kind?: T;
        required?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  bundleItems?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  user?: T;
  customerEmail?: T;
  customerName?: T;
  customerPhone?: T;
  items?:
    | T
    | {
        productTitle?: T;
        product?: T;
        bundleParentLineId?: T;
        quantity?: T;
        unitPrice?: T;
        customFieldValues?: T;
        id?: T;
      };
  subtotal?: T;
  total?: T;
  currency?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  menuLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'news';
                value: string | News;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Optional sub-links shown on hover. Dropdowns cannot nest further — max depth is two.
         */
        dropdown?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'news';
                      value: string | News;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Displayed as the footer heading.
   */
  clubName?: string | null;
  /**
   * Short sentence shown beneath the club name.
   */
  tagline?: string | null;
  /**
   * Optional nav links rendered in the footer. Flat list — no dropdowns in the footer.
   */
  menuLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'news';
                value: string | News;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Copyright line shown in the sub-footer. Use {year} as a placeholder (e.g. "© {year} - La Salle Handball Club").
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general".
 */
export interface General {
  id: string;
  general: {
    name: string;
    description: string;
    logo?: (string | null) | Media;
    favicon?: (string | null) | Media;
    fallbackImage?: (string | null) | Media;
  };
  reading?: {
    /**
     * Enter the number of posts to show per page.
     */
    postsPerPage?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  menuLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        dropdown?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  clubName?: T;
  tagline?: T;
  menuLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general_select".
 */
export interface GeneralSelect<T extends boolean = true> {
  general?:
    | T
    | {
        name?: T;
        description?: T;
        logo?: T;
        favicon?: T;
        fallbackImage?: T;
      };
  reading?:
    | T
    | {
        postsPerPage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}