import './globals.css'
import './fonts.css'
import Footer from '@/components/Footer/Footer'
import { ApolloWrapper } from '@/lib/utils/apollo/apollo-wrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          {children}
          <Footer />
        </body>
      </html>
  )
}
